team-Fithub/fithub-backend

- src/main/java/com/fithub/fithubbackend/global/common/BaseTimeEntity.java
- src/main/java/com/fithub/fithubbackend/global/exception/CustomException.java
- src/main/java/com/fithub/fithubbackend/global/exception/CustomExceptionHandler.java
- src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java
- src/main/java/com/fithub/fithubbackend/global/exception/ErrorResponseDto.java
- baseTimeEntity 필드명 수정
- 코드 작성 하는데 에러 핸들러 미리 만드는게 나을 것 같아서 추가 (에러 코드는 추후에 상의 후 양식 변경)
> feat: 에러 핸들러, 에러 코드 추가

- src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableDate.java
- src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableTime.java
- src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainerInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingCreateDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingOutlineDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerRepository.java
- 트레이닝 관련 엔티티, dto, repo, service, controller 추가
- 트레이너: 트레이닝 생성 기능 추가, 수정/삭제는 예약 기능과 함께 진행할 예정
- 일반 회원: 트레이닝 전체 조회, 상세 조회 기능 추가
안 되는 date를 받아서 그 날 빼고 calendar로 날짜 리스트 받아온 후 지정한 시간들을 넣어줌
```
GET http://localhost:8080/users/training/all
```
```
{
"content": [
{
"id": 3,
"trainerInfoDto": {
"trainerId": 1,
"name": "garamName",
"trainerProfileImg": null,
"location": "경기도 경기도"
},
"title": "트레이닝 생성",
"price": 10000,
"location": "트레이닝 할 트레이너 위치",
"startDate": null,
"endDate": null,
"closed": false
},
...
}
```
```
GET http://localhost:8080/users/training?trainingId=3
```
```
{
"id": 3,
"trainerInfoDto": {
"trainerId": 1,
"name": "garamName",
"trainerProfileImg": null,
"location": "경기도 경기도"
},
"title": "트레이닝 생성",
"content": "트레이닝 생성 내용",
"location": "트레이닝 할 트레이너 위치",
"quota": 10,
"price": 10000, …
```
> feat/training: 엔티티, dto, repo, service, controller 기본 코드 추가 및 생성,조회 기능 추가

- src/main/java/com/fithub/fithubbackend/domain/user/domain/Comment.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/Document.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/Hashtag.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/Likes.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/Post.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/PostDocument.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/PostHashtag.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
- 게시글 및 프로필 기본 정보 추가
- 회원의 이미지 필드의 타입 및 연관 관계 수정 ( String -> Document )
> feat: 게시글(댓글, 해시태그, 좋아요), 프로필 기본 정보 추가 

- build.gradle
- src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainerInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingCreateDto.java
- src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
- 로그인, 회원가입 추가 시 PERMIT_ALL_PATTENRS에 추가 필요
- 필터 추가 시 .addFilterBefore() 추가 필요
- exception 핸들링 추가, oauth2 설정 추가 필요
> feat/auth: SecurityConfig, Swagger 추가

- src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/UserDetailsServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/user/dto/SignOutDto.java
- src/main/java/com/fithub/fithubbackend/global/util/CookieUtil.java
- 코드 수정
- main -> main
- 로그인 시, 사용자 정보가 없는 경우 예외 처리 한 번만 수행
- 로그아웃 시, 불필요한 refreshToken 파라미터 삭제
> refactor: 로그인 예외 처리 및 로그아웃 파라미터 수정

- src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/EmailServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/user/dto/SignUpDto.java
- src/main/java/com/fithub/fithubbackend/domain/user/dto/constants/SignUpDtoConstants.java
- 오류 수정 및 피드백 반영
- refactor/feedback -> main
- 비밀번호 패턴 오류 수정
- swagger request 값 변경
- 데이터 형식 오류 메세지 수정
- 이메일 인증번호 변경 (영문 숫자 조합 6자리)
> refactor: 피드백 반영 

- src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
- src/main/java/com/fithub/fithubbackend/domain/user/enums/Gender.java
- src/main/java/com/fithub/fithubbackend/global/auth/OAuthAttributes.java
- src/main/java/com/fithub/fithubbackend/global/auth/OAuthService.java
- src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java
- 기능 추가
- main -> main
- 네이버 소셜 로그인 기능 추가
> 필수 제공 항목 : 이메일 주소, 닉네임
> 추가 제공 항목 : 휴대 전화 번호, 이름, 성별
> feat: 네이버 소셜 로그인 추가

- src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/AuthService.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
- src/main/java/com/fithub/fithubbackend/global/config/s3/AwsS3Uploader.java
- src/main/java/com/fithub/fithubbackend/global/config/s3/S3Config.java
- src/main/java/com/fithub/fithubbackend/global/domain/Document.java
- src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java
- 기능 추가
- featrue/profileimg -> main
- 회원가입 시 프로필 이미지 업로드 기능 추가
- Document의 변수들이 notnull이라서 이미지 파일 미 첨부 시 기본이미지를 넣어주어야 할 것 같습니다.
> feat: 프로필 이미지 업로드

- src/main/java/com/fithub/fithubbackend/domain/user/application/EmailServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/user/dto/EmailNumberDto.java
- 인증번호 검증 수정
- update/email -> main
- 이메일에 발송한 인증번호 검증 로직 수정
> update: 인증번호 검증 수정

- src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
- src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java
- src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
- 기능 수정
main -> main
1. 예외 핸들링 수정 (지난 전 pr로 인해 없어진 핸들링 다시 추가)
2. 소셜 회원가입 시 email 정보 보내주도록 수정
3. 회원가입 시 에러가 났던 이유 발견 후 수정 (requestParam에 value 추가, consumes 추가)
> fix: 회원가입 수정

- src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingLikesInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingLikesRepository.java
- 기능 추가
feature/training -> main
- 트레이닝 찜 리스트 조회 api 추가
> feat: 트레이닝 찜 리스트 조회

- src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/domain/Trainer.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerRepository.java
- src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
- 기능 추가, 수정
1. 트레이너 작업 시에 TRAINER 권한 검사
2. 트레이너 인증 요청 승인 시 TRAINER 권한 부여
3. 트레이닝 게시글 수정 시 해당 트레이너가 수정하는 건지 확인
- 인증 요청 승인 시 
ROLE 추가 됨
- 트레이닝을 생성한 트레이너가 아닌데 수정을 시도할 경우
> Feature/training: 트레이너 ROLE 추가, 트레이닝 수정 시 트레이너 확인 과정 추가

- src/main/java/com/fithub/fithubbackend/domain/user/application/UserDetailsServiceImpl.java
- src/main/java/com/fithub/fithubbackend/global/domain/UserAdapter.java
- loadUserByUsername에서 userAdapter 반환으로 수정하지 않으셨어서 에러 발생
- UserAdapter에 권한 부여 에러 (ROLE_[ROLE_USER,ROLE_TRAINER])이런 식으로 됐었음. ROLE_USER,ROLE_TRAINER로 되도록 수정
> fix: UserAdapter 에러 수정

- src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java
- 수정
- feature/post -> main
- 네이버 로그인 성공 시 권한 (ROLE_GUEST -> ROLE_USER) 수정
- 네이버 로그인 성공하면 url에 accessToken 잘 넘어감
> update: 네이버 로그인 성공 시 권한 변경

- src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java
> auth: 소셜 로그인 시 토큰반환을 프론트에서 받을 수 있는지 확인용 pr (임시)

- src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/domain/TrainingReview.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingReviewInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingReviewReqDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/UsersReserveInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/UsersTrainingReviewDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingReviewRepository.java
- src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
- src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
- 기능 추가
1. 트레이닝 예약 내역 조회 메서드에 트레이닝 예약 정보 id 추가
2. 트레이닝 예약 내역에 후기 작성 crud 추가
- 예약한 사람과 후기 작성 사용자가 같지 않을 때
- 후기 작성 성공
- 후기 조회
- 트레이닝 상세 조회 시 리뷰 리스트 조회
> Feature/training: 트레이닝 예약에 대한 후기 작성 crud

- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingReviewDto.java
- src/main/java/com/fithub/fithubbackend/domain/user/dto/UserNicknameAndProfileDto.java
- 수정
- 미업로드된 트레이닝 리뷰 관련 dto 파일 업로드
> fix: 트레이닝 리뷰 관련 dto 미업로드 파일 추가

- src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
- 기능 수정
- 트레이너 인증 요청 승인 시 현재 일하는 곳이 있으면 가져오고 없으면 null 갖도록 했는데 orElseGet부분에서 null을 담을 때 에러 발생. null을 담는게 아닌 optional로 가져와서 체크하도록 함
> fix: 트레이너 인증 요청 승인시 null 에러 수정

- .gitignore
- build.gradle
- src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingSearchConditionDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/repository/CustomTrainingRepository.java
- src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/AuthService.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/user/dto/oAuthSignInDto.java
- src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
- src/main/java/com/fithub/fithubbackend/global/config/QuerydslConfig.java
- src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
- 기능 추가, 수정
- querydsl 추가
- 트레이닝 검색 기능 추가: 키워드, 최저/최고가, 시작/마감일 필터 사용
- 소셜 로그인 발급 시 기존에는 email, provider를 requestParam으로 받았는데 requestBody로 받도록 수정
> Feature/training: 트레이닝 검색 기능 추가/ update: 소셜 로그인 토큰 발급 시 필요 정보 dto로 받도록 변경

- src/main/java/com/fithub/fithubbackend/domain/user/api/UserController.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/UserService.java
- src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
- src/main/java/com/fithub/fithubbackend/domain/user/dto/ProfileUpdateDto.java
- src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java
- 기능 수정
- feature/profile-> main
- 세 개의 api로 분리
-  /users/profile/update (get): 수정 페이지
- /users/profile/update (put): 수정 
- /users/image/update (put) : 이미지 업데이트
> GET /users/profile/update
> PUT  /users/profile/update
> GET /users/image/update 
- 채팅 entity 작성
> fix: 프로필 업데이트 수정

- src/main/java/com/fithub/fithubbackend/global/config/RedisConfig.java
- 설정 수정
- 서버 redis 봇 해킹으로 비밀번호 설정됨
- application.yml - redis 부분에 password 추가 (노션 참고)
> feat: redis 비밀번호 설정

- src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingLikesController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingLikeService.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingLikeServiceImpl.java
- 기능 추가
- 회원이 트레이닝 전체 조회 시 찜 여부 확인
> feat: 트레이닝 page 조회 시 id 목록 받아서 좋아요 여부 확인

- src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingLikesController.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/TrainersReserveInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/repository/CustomReserveInfoRepository.java
- 기능 수정
- 트레이너의 예약 리스트 응답 데이터에 reservation id 추가
- 주어진 트레이닝 목록의 찜 여부 조회 api에 swagger 수정
- QTrinerReserveInfoDto 수정으로 compileJava 필요
> update: 트레이너의 예약 리스트 응답 데이터 id 추가, 트레이닝 목록 찜 여부 조회 swagger 수정

- src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainersTrainingOutlineDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingContentUpdateDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingCreateDto.java
- 엔티티 수정
- 기존에 트레이닝 모집 인원(정원)을 받을 수 있었는데 무의미하여 삭제
- 엔티티, dto에서 삭제
- 엔티티 수정으로 compileJava 필요
> feat: 트레이닝에서 모집 인원(정원) 컬럼 삭제

- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/Location.java
- src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerController.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerCertificationRequestDto.java
> Refactor: 트레이닝, 트레이너 관련 코드 리팩토링

- src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableTimeRepository.java
- src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
- src/main/java/com/fithub/fithubbackend/global/component/Scheduler.java
- 기능 추가
- 트레이닝 예약 취소 가능 기한이 있어서 트레이닝 당일 취소 불가로 변경
- 트레이닝 수동으로 마감 또는 오픈 시 availableDate, Time도 enabled = false / true로 변경
> feat: 트레이닝 당일 취소 불가, feat: 트레이닝 수동 마감,오픈 시 날짜,시간도 마감,오픈

- src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerController.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerService.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerCareerDetailDto.java
- src/main/java/com/fithub/fithubbackend/global/exception/CustomExceptionHandler.java
- 기능 수정
- 트레이너 정보 조회에서 쓰이는 경력 조히 dto: 사용하지 않는 address 삭제
- 트레이너 경력 수정을 위해 경력 하나 상세 조회 dto에 좌표 추가
> update: 트레이너 경력 하나 조회 수정

- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
Training -> training으로 테이블 이름 수정
> fix: 트레이닝 위치로 조회 query 에러 수정

- src/main/java/com/fithub/fithubbackend/domain/admin/api/AdminController.java
- src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminService.java
- src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/admin/dto/ApplicantInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/admin/dto/CertRejectedRequestDto.java
- src/main/java/com/fithub/fithubbackend/domain/admin/dto/CertRequestDetailDto.java
- src/main/java/com/fithub/fithubbackend/domain/admin/dto/CertRequestOutlineDto.java
- src/main/java/com/fithub/fithubbackend/domain/admin/dto/TrainerCareerTempDto.java
- src/main/java/com/fithub/fithubbackend/domain/admin/dto/TrainerLicenseTempImgDto.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerCertificationRequestRepository.java
- 기능 추가
- 관리자-트레이너 인증 요청  api trainer/certificate -> trainers/authentications로 변경
- 트레이너 인증 요청 전체 조회, 상세 조회 추가
- 트레이너 인증 요청 전체 조회
- 트레이너 인증 요청 반려 기록 전체 조회
- 트레이너 인증 요청 상세 조회
> Feature/admin: 관리자-트레이너 인증 요청 조회 기능 추가

- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingContentUpdateDto.java
- src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingImgUpdateDto.java
- src/main/java/com/fithub/fithubbackend/domain/board/dto/PostUpdateDto.java
- 기능 수정
- 프론트에서 트레이닝 이미지 수정을 하지 못 하는 것 발견.
- dto를 따로 받고있는데 그걸 제가 수정할 방법을 모르겠어서 그냥 한번에 받도록 백엔드를 수정함
> fix: 트레이닝 수정 시 이미지 관련 dto 받는 곳 수정

- src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/chat/repository/ChatRepository.java
> fix: chatRepository 쿼리 에러 수정

- src/main/java/com/fithub/fithubbackend/domain/trainer/application/UserTrainerServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/trainer/repository/CustomTrainerRepositoryImpl.java
- 기능 수정
- main -> main
- 트레이너 검색 및 추천 시 탈퇴한 트레이너 정보가 노출되지 않도록 수정
> update: 탈퇴한 트레이너인 경우 트레이너 검색 및 추천 시 노출되지 않도록 수정

- src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
- src/main/java/com/fithub/fithubbackend/global/notify/NotificationType.java
- src/main/java/com/fithub/fithubbackend/global/notify/dto/NotifyRequestDto.java
- 기능 수정, 추가
- 알림 url 프론트 페이지 이동을 위해 url을 프론트에서 지정한 페이지로 수정
- 트레이너가 예약 노쇼 처리 시, 예약했던 사람에게 노쇼 처리 됐다고 알림 추가
> update: 알림 타입별 url 수정, feat: 예약 노쇼 처리 시 예약자에게 알림 추가

- src/main/java/com/fithub/fithubbackend/domain/board/application/CommentService.java
- src/main/java/com/fithub/fithubbackend/domain/board/application/CommentServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/board/application/PostServiceImpl.java
- src/main/java/com/fithub/fithubbackend/domain/board/dto/PostInfoDto.java
- src/main/java/com/fithub/fithubbackend/domain/board/repository/CommentRepository.java
- 기능 수정
- main -> main
- 게시글 댓글 수 조회 시, 최상단 댓글 대신 전체 댓글 수 조회하도록 수정
> update: 게시글 댓글 수 조회 수정 
