build.gradle
src/main/java/com/fithub/fithubbackend/domain/user/api/UserController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserDetailsServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/SignInDto.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/SignOutDto.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/UserDto.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserRepository.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtExceptionFilter.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtTokenProvider.java
src/main/java/com/fithub/fithubbackend/global/auth/TokenInfoDto.java
src/main/java/com/fithub/fithubbackend/global/config/RedisConfig.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java
src/main/java/com/fithub/fithubbackend/global/util/CookieUtil.java
src/main/java/com/fithub/fithubbackend/global/util/HeaderUtil.java
src/main/java/com/fithub/fithubbackend/global/util/RedisUtil.java

- 기능 추가
- Spring Security, Jwt, Redis 이용한 로그인/로그아웃/토큰 재발급 기능 추가
> POST /user/auth/sign-in
1. RequestBody로 이메일, 비밀번호를 전달 받음.
`{
"email": "test@test.com",
"password": "testtest"
}`
2. 로그인 성공 시, TokenInfoDto 전달 및 쿠키에 저장 **(HTTP Status Code : 200)**
- accessToken 유효 기간 : 30분 / refreshToken 유효 기간 : 7일
3. 로그인 실패 시
- 아이디가 DB에 없을 경우 **(HTTP Status Code : 404)**
- 비밀번호가 틀린 경우 **(HTTP Status Code : 403)**
3. Redis에 키(email), 값(refreshToken)으로 저장.
<hr>
> DELETE /user/auth/sign-out
1. 로그아웃 성공 시 **(HTTP Status Code : 200)** 
2. 실패 시  **(HTTP Status Code : 403)** 
<hr>
> PATCH /user/auth/reissue
1. 재발급 성공 시 TokenInfoDto 전달 **(HTTP Status Code : 200)** 
2. 실패 시  **(HTTP Status Code : 403)** 
<hr>
- refreshToken 유효 기간 동안 자동 로그인 실행
- application.yml에 redis, jwt 관련 환경 변수 추가 ( Notion …

feat: SpringSecurity, Jwt, Redis 이용한 로그인/로그아웃/토큰 재발급 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
src/main/java/com/fithub/fithubbackend/domain/user/enums/Gender.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserRepository.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthAttributes.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthService.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가 (구글 로그인)
- auth -> main
- OAuthAttribute 추가 (현재는 구글만 있음)
- 소셜 로그인 처리하는 서비스, 핸들러 추가
- SecurityConfig에 oauth2 설정 추가
- User 프로필 이미지 null 허용으로 변경 (이미지가 지금 들어가지 않는 경우가 많은데 null 허용이 아니다 보니 복잡해져서 우선 허용해놨습니다)
http://localhost:8080/oauth2/authorization/google    
진입 시
구글 로그인 창으로 이동
계정 선택 시
oAuthService 진입됨
유저 생성 or 업데이트 후
성공 핸들러로 이동해서 토큰 발급 성공
프론트와 상의 후 소셜 로그인 성공 후, 회원 정보를 입력할 수 있는 페이지로 이동해야됨.
redirect 주소 수정 필요

feat: 구글 소셜 로그인 추가

---

src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthService.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java

- 기능 수정
- auth -> main
1. 소셜 로그인 시 saveOrUpdate에서 .orElse로 상황에 상관없이 접근해서 .orElseGet으로 변경
2. 소셜 회원가입 시에는 role을 GUEST로 줘서 회원가입이 완료된 회원인지 아닌지 확인할 수 있는 방법 추가
3. 소셜 작업 성공 시 role에 GUEST가 있으면 추가 정보 입력이 필요한 회원으로 판별해 정보 입력을 하는 url로 이동하도록 추가
- 노션 application.yml에 redirect 주소 추가
프론트에서 배포 링크 주면 그걸로 application.yml에 redirect 주소 수정 후 서버 배포 필요

update: 소셜 회원가입 권한 수정, 회원가입/로그인에 따라 성공 로직 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/TrainingLikes.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingLikesRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/Trainer.java

- 기능 추가
1. Trainer 빌더 추가
2. Training 엔티티에서 Trainer fetchtype LAZY로 수정
3. 트레이닝 찜 엔티티 추가
4. 찜 여부 조회, 찜 설정/해제 기능 추가
1. 찜 여부 조회
2. 찜 설정/해제 기능
- 설정
- 해제
회원에 대한 정보를 가져올 때 AuthenticationPrincipal을 사용해서 UserDetails를 가져오는데 이러면 메소드 안에서 회원을 사용해야 할 때 다시 인증할 때처럼 userRepository에 접근하는 비용 발생. (ex. db에 저장할 일이 필요하면 대부분 사용자 id (primary key)가 필요한데 userDetails로는 얻을 수 없음)
userRepo -> documentRepo -> roleRepo 접근해서 인증 후에 또 메소드에서 userRepo -> documentRepo로 접근하는 상황이 발생하는데 이때 loadByUsername을 User로 가져오게 하고 Authentication에 user를 저장하는 것과 그냥 지금처럼 userDetails를 사용하는거 중에서 어떤게 더 안전하고 효율적인 선택지인지 고민

feat/training: 회원-트레이닝 찜 여부 조회, 찜 설정 / 해제 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtExceptionFilter.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java
src/main/java/com/fithub/fithubbackend/global/util/CookieUtil.java

- 에러 수정, 기능 수정
- main -> main
- 로그인 시, 비밀 번호 틀린 경우 403 에러 발생하도록 수정 
- 로그인, 로그아웃, 토큰 재발급 error 관련 api-response 수정
- access Token은 cookie 대신 response body로 전달하도록 수정
- refresh Token 쿠키 생성 시, secure 옵션 True로 설정
- access Token 유효 기간 만료 및 refresh Token 유효한 경우, access Token을 새로 발급하여 response body에 토큰과 201 코드 전달
- 로그인
- 수정 전 
> 비밀번호가 틀려도 HTTP 상태 코드 200 전달
- 수정 후 
> 비밀번호가 틀릴 경우 BadCredentialsException 에러 발생 시켜 HTTP 상태 코드 403 코드 전달
- 토큰 재발급
- access Token 유효 기간 만료 및 refresh Token 유효한 경우, access Token을 새로 발급하여 response body에 토큰과 201 코드 전달

update: 로그인 시 비밀번호 틀린 경우에 대한 예외 처리 추가, 토큰 관련 응답 결과 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainerInfoDto.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthService.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java

- 에러 수정
- main -> main
- TrainerInfoDto profileImg 변수명 변경
- customAttribute에 email 값 추가
- user의 role이 guest가 아닌 경우 uri의 파라미터로 액세스 토큰 전달
- user의 role이 guest가 아닌 경우 redirect-uri 퀴리로 액세스 토큰 전달 
> http://localhost:3000/?accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7aWQ9UzE2d1p2NWJHWE1YN3o5d2xRMUhSQkpocTR3dF9YaUE2Zk4ycDd0NC1fQSwgbmlja25hbWU9azI2OTksIGVtYWlsPWtqcjI2OTlAbmF2ZXIuY29tfSIsImF1dGgiOiJVU0VSIiwiZXhwIjoxNzAyMTA2MDI5fQ.R2ExllDiUVAOeDO62A6JXGRRapmrrmmqXz-_N36FzBI

update: 소셜 로그인 성공 시 액세스 토큰을 리다이렉트 URI의 쿼리로 전달

---

src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtTokenProvider.java

- 기능 추가
- auth ->main
- 소셜 회원가입 시 토큰 발급을 위해 createToken 메소드 오버로딩 (소셜 회원가입시에는 authentication 대신 email로)
- 소셜 회원가입 후에 추가 정보 입력 -> 성공하면 토큰 발급

feat/auth: 소셜 회원가입 후 토큰 발급

---

src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerAuthController.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthService.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/Trainer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareerTemp.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCertificationRequest.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerLicenseImg.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerLicenseTempImg.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerCareerRequestDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerCertificationRequestDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerCertificationRequestRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
src/main/java/com/fithub/fithubbackend/global/auth/CustomAuthenticationEntryPoint.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
src/main/java/com/fithub/fithubbackend/global/config/s3/AwsS3Uploader.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java

- 기능 추가, 수정
- feature/trainer-> main
1. s3에서 에러 던지는 걸 try-catch로 수정
2. 사용자 프로필 기본 imgPath에 폴더명 추가
3. 인증 실패 시 response가 현재 security login 창으로 이동인데 이걸 인증 실패 response 반환으로 수정
4. 트레이너 인증요청,자격증, 임시 자격증,경력사항, 임시 경력사항 엔티티 추가
5. 트레이너 인증 요청 기능 추가
6. role관련 ROLE_ prefix 추가
요청 후 s3에 파일 업로드,  db 저장 완료

feat/trainer: 트레이너 인증 요청 추가, fix:role prefix 수정

---

src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/SignOutDto.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtExceptionFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가
- SignOutDto 빌더 수정
- 로그아웃 파라미터 수정
-  jwt 예외 관련 response json 형식 수정
- 로그아웃, 토큰 재발급 시 예외 처리하는 try-catch 추가
- SHOULD_NOT_FILTER_URI_ALL_LIST 에 토큰 재발급 api 삭제
- 유효한 refresh Token만 쿠키에 있을 경우, access Token 재발급
> 1. access Token 유효 X / refresh Token 유효 X
`{
"code": 405,
"httpStatus": "405 METHOD_NOT_ALLOWED",
"message": "재로그인 필요"
}`
> 2. access Token 유효 X /  refresh Token 유효 O
`{
"code": 201,
"httpStatus": "201 CREATED",
"message": "30분 유효 기간 지나 access Token 재발급 성공",
"accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmaW5hbEBmaW5hbC5jb20iLCJhdXRoIjoiR1VFU1QiLCJleHAiOjE3MDI2MTQ1NzV9.IB2iLGk6bPjF1Dxp8gSBoYY8CBo5hY86PRWQgXybC_g"
}`
> 1. redis에 refresh Token 존재 X 및 refresh Token 유효 X
`{
"code": 405,
"httpStatus": "405 METHOD_NOT_ALLOWED",
"message": "재로그인 필요"
}`
> 2. …

update: 로그인 완성

---

build.gradle
src/main/java/com/fithub/fithubbackend/FithubBackendApplication.java
src/main/java/com/fithub/fithubbackend/domain/user/api/MapController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/EmailServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/application/MapService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/MapServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/constants/MapDocumentDto.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/constants/MapDto.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java
src/main/java/com/fithub/fithubbackend/global/util/KakaoMapUtil.java

- 기능 추가, 수정
- feature/map-> main
1. 인증번호 중복 발행 시 이전에 있던 인증번호 삭제
2. 위치를 입력받고 위치에 따른 주변 헬스장 조회
- 카카오 Map을 사용했는데 카카오에서 조회시 최대 개수를 45개로 정해놔서 검색 결과 개수가 45개를 넘어가도 45개까지만 나옵니다. 좀 더 많은 결과를 보여주는 openApi가 있다면 바꾸는게 좋을까요?

feat: 주변 헬스장 조회, fix: 인증번호 중복 발행 에러 수

---

src/main/java/com/fithub/fithubbackend/domain/admin/api/AdminController.java
src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminService.java
src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/admin/domain/TrainerCertificationRejectLog.java
src/main/java/com/fithub/fithubbackend/domain/admin/dto/CertRejectDto.java
src/main/java/com/fithub/fithubbackend/domain/admin/enums/RejectType.java
src/main/java/com/fithub/fithubbackend/domain/admin/repository/TrainerCertificationRejectLogRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/Trainer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareerTemp.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCertificationRequest.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerLicenseImg.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerLicenseTempImg.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerCertificationRequestRepository.java

- 기능 추가
- feature/trainer -> main
- 트레이너 엔티티에 경력, 자격증 사진 리스트 추가
- 트레이너 인증 요청 엔티티에 반려 여부 추가
- 트레이너 인증 요청 반려 기록 엔티티 추가
- 트레이너 인증 요청 승인, 반려 기능 추가
- 트레이너 인증 요청 시 인증 요청이 있는지 검사 -> 반려되지 않은 인증 요청이 있는지 검사로 변경 (반려된 인증 요청는 경우에는 신청 가능)
1. 승인
트레이너, 트레이너 자격증 사진, 트레이너 경력사항 엔티티에 추가 됨
2. 반려
트레이너 인증 요청 반려 기록에 추가
rejected를 true로 설정
- 승인, 반려 시 회원에게 알림
- 반려된 내용을 어드민이 볼 수 있도록 (다른 작업 다 하고 나서 진행할듯)

feature/trainer: 트레이너 인증 요청 승인, 반려 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/board/application/BookmarkServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/LikesServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostDocumentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostHashtagServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostService.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/Bookmark.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/Likes.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/Post.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/PostDocument.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/PostHashtag.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/PostHashtagRepository.java

- 기능 수정
- feature/post-> main
- 게시글 조회 위해 관련 entity(이미지, 해시태그, 북마크, 좋아요) 양방향 연관 관계로 수정 
- 해시태그  업데이트 기능 수정
- 기존 코드에서 게시글 해시태그 수정한 후, 게시글 정보를 불러올 때 유저가 수정한 순서대로 불러오지 않는 문제 발생
- 기존 해시태그와 수정된 해시태그를 비교하고, 다르다면 기존 해시태그들을 삭제 후 새로 생성하도록 수정 
-> **변경 사항이 거의 없을 경우 비효율적이라 사용 X**
- post의 content에 내용과 해시태그 같이 저장 
-> **해시태그 테이블을 쓰는 의미가 없어 사용 X**
- 기존 포스트 해시태그의 해시태그 fk 수정 및 추가하는 방식으로 수정
> 해시태그 수정 전
> 해시태그 수정 후

update: 게시글 관련 entity 양방향 연관 관계로 수정, 해시태그 업데이트 기능 수정

---

build.gradle
src/main/java/com/fithub/fithubbackend/domain/Training/api/PaymentController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableDate.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableTime.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/ReserveInfo.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/CancelReqDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/PaymentReqDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/PaymentResDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/ReserveReqDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/enums/ReserveStatus.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserRepository.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/exception/CustomExceptionHandler.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java

- 기능 추가
1. 포트원(아임포트) 추가
2. 예약 엔티티 생성
3. 예약(결제) 기능 추가
4. 예약(결제) 취소 기능 추가
- application.yml에 포트원 관련 키 추가
! 실제 결제가 되는지는 프론트 페이지가 완성되고 결제 시도 후에 알 수 있을 듯
- 결제 완료 후 예약 생성
트레이닝 예약 가능 시간이 가능 -> 불가능으로 바뀌고 만약 예약한 날짜의 예약 가능 시간대가 없다면 예약 가능 날짜가 불가능으로 바뀌는 것도 확인
- 예약 취소
트레이닝의 예약 가능 시간들이 불가능 -> 변경으로 바뀌는 것까지 확인

Feat/training: 예약(결제) 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/PaymentController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/api/CommentController.java
src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/CommentService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/CommentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerAuthController.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthService.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
src/main/java/com/fithub/fithubbackend/domain/user/api/UserController.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java

- 수정
auth -> main
- AuthenticationPrincipal로 얻어오던 UserDetails를 AuthUser 인터페이스 사용으로 User를 얻어올 수 있게 됨. 따라서 user를 한 번더 조회하지 않도록 수정
- 이메일 인증 시 필터에서 제외되지 않아 토큰 에러 상황 발생 -> 필터에서 이메일 인증 부분 제외

update: AuthenticationPrincipal -> AuthUser로 수정, 이메일 인증 에러 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/ReserveInfo.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainersReserveInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/UsersReserveInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/enums/ReserveStatus.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java

- 기능 추가
1. 트레이너의 예약 리스트 조회 기능 추가
2. 회원의 예약 리스트 조회 기능 추가 (추후에 진행 상황(진행정, 진행중, 완료, 취소)에 따라 나눠서 보내줄지 아니면 프론트에서 나눌지 상의 필요)
- 트레이너의 예약 리스트 조회 (자신이 올린 트레이닝에 예약된 내용 조회)
- 회원의 트레이닝 예약 리스트 조회 (자신이 예약한 트레이닝 조회 - 현재는 생성 순이지만 프론트에서 정렬 기준 주면 변경)

Feat/training: 트레이닝 예약 리스트 조회 기능 추가(회원,트레이너)

---

src/main/java/com/fithub/fithubbackend/FithubBackendApplication.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableDateRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableTimeRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/global/component/Scheduler.java
src/main/java/com/fithub/fithubbackend/global/config/SchedulerConfig.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java

- 기능 추가
1. 트레이닝 예약(결제)/취소(환불) 시 트레이닝 마감 설정,해제 추가
2. 스케줄러 설정 추가
3. 트레이닝 자동 마감 스케줄러 추가 (1시간마다 실행)
4. 트레이닝 수동 마감, 오픈 기능 추가
1. 트레이닝 마감 -> 오픈으로 변경 시 변경할 트레이닝의 예약 가능 마지막 날짜가 현재 날짜보다 이전일 경우 에러 발생

Feature/training: 트레이닝 마감(스케줄러, 수동), 오픈(수동) 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/board/api/CommentController.java
src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/CommentService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/CommentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/comment/domain/Comment.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/CommentInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/LikesInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/Post.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/CommentRepository.java

- 기능 추가 
- feature/post -> main
- 게시글 전체, 세부 조회 
> GET /posts
- liked, bookmark -> 로그인한 사용자의 게시글 좋아요, 북마크 여부 확인
- 전체 조회는 댓글 리스트 대신 댓글 개수만 확인 가능
> GET /posts/{postId}
- "deleted" -> 댓글 삭제 여부 체크
- 댓글 수는 deleted가 true인 댓글 제외하고 카운트
> GET /posts/{postId}
- 댓글 조회 기능을 두 가지 방법으로 구현했는데 어떤 방법이 편한지 게시글 담당자분과 얘기 나눠보겠습니다!

feat: 게시글 전체, 세부 조회 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingLikesRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java

- 기능 추가, 수정
1. 기존: 트레이닝 찜 설정을 파라미터로 구분 -> 변경: 트레이닝 찜과 취소를 분리
2. training에 deleted 컬럼 추가 (soft delete)
3. 트레이닝 삭제 기능 추가
4. 트레이닝 조회 시 deleted = true 제외
5. SecurityConfig, JwtAuthenticationFilter에 거치지 않아야되는 api 추가
- 트레이닝 삭제 시 진행전/진행 중인 트레이닝 예약이 있다면

Feature/training: 트레이닝 찜/취소 분리, 트레이닝 삭제 기능 추가, filter 거치지 않을 api 추가

---

src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtExceptionFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
src/main/java/com/fithub/fithubbackend/global/util/CookieUtil.java
src/main/java/com/fithub/fithubbackend/global/util/HeaderUtil.java

- 수정
- 액세스 토큰 쿠키 대신 헤더에서 추출
- 일반 및 소셜(카카오, 구글) 로그인 성공 시 액세스 토큰 헤더에 추가
> POST /auth/sign-in
- 소셜 회원 가입 후 로그인하게 되면 토큰 dto를 response body에 넣어야 하는데, redirect 이라 HttpServletResponse이 새로 생성되면서 dto가 넘어가지 않는 문제가 생기네요... 
- 구글링해보니 UriComponentsBuilder의 queryParam로 전달하는 경우가 꽤 있는데 보안 상 문제가 발생할 수 있어서 좀 더 생각해봐야 될 것 같아요! ;(

update: 액세스 토큰 쿠키 대신 헤더에서 추출, 일반 및 소셜(카카오, 구글) 로그인 성공 시 액세스 토큰 헤더에 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingAvailableDateDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingAvailableTimeDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserRepository.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthFailureHandler.java
src/main/java/com/fithub/fithubbackend/global/auth/OAuthSuccessHandler.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 수정, 추가
- update -> main
1. 소셜 로그인 -> 성공 -> 리다이렉트(파라미터에 socia_login true값을 줌?) -> socia_login = true면 프론트에서 /auth/oauth/login 요청 -> 백에서 토큰 설정
2. 소셜 로그인 -> 실패 -> 실패 시 보여줄 페이지로 리다이렉트 (파라미터에 실패 이유 포함 (http://localhost:3000/oauth/fail)) -> 프론트에서 처리
3. 소셜 로그인 시 토큰 반환 X. 어차피 헤더에 설정해주니까 반환할 필요 없다고 생각. "완료"라고만 보내줌
4. 일반 회원가입 이메일 중복 체크할 때 소셜로 있는 이메일이면 어떤 소셜로 있는 건지 알려줌
- 소셜 로그인 성공 후 토큰 발급: /auth/oauth/login?email=~ &provider=~
- 소셜 로그인 성공 후 토큰 발급: 토큰 발급할 때 주어진 이메일과 provider가 db에 저장된 것과 다르면 
- 소셜 회원가입: 이미 일반 회원가입이 진행된 이메일이라면
- 일반 회원가입: 이미 소셜 회원가입이 진행된 이메일이라면

Update: 소셜 로그인 성공, 실패 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableDate.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/global/component/Scheduler.java

- 기능 수정
트레이닝 마감 스케줄러
- 기존에는 시간 체크 후( 트레이닝 마감일 && 마지막 시간이 현 시간)이면 트레이닝 전체 마감만 했는데, 매 시간마다 체크하는 스케줄러이다 보니 트레이닝 예약 가능 날짜가 오늘이고, 오늘 예약 가능한 시간들 중에 스케줄러가 돌아간 시간이면 (예약 불가능한 상태) 지났으면 그 시간도 마감하도록 추가
- 시간 마감 후, 해당 트레이닝에 오늘 더 이상 가능한 예약 시간이 없으면 오늘 날짜도 마감되도록

update: 트레이닝 마감 스케줄 작동 시 트레이닝 예약 시간도 마감하도록 수정

---

src/main/java/com/fithub/fithubbackend/domain/board/api/CommentController.java
src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/LikedUsersInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/LikesInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostCreateDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostDetailInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostDocumentUpdateDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostWriterInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/Post.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/PostHashtagRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/PostRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
src/main/java/com/fithub/fithubbackend/domain/user/api/EmailController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/application/EmailService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/EmailServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/PasswordUpdateDto.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가, 수정
- 비밀번호 찾기 기능 추가
- JwtAuthenticationFilter, SecurityConfig에 인증 필요 없는 api 추가 (게시글 전체, 세부 조회 api / 비밀번호 변경 api)
- 게시글 세부 조회 시에만 댓글 리스트 확인 가능, 
- stream의  limit 사용하여 게시글 좋아요 리스트 최대 3개까지만 가져오도록 수정
- 게시글 조회 리팩토링 (@entitygraph 사용하여 게시글 조회 시 연관된 객체 불러오기)
- 게시글 정보 Dto 세분화
- 임시 비밀번호 이메일로 전송
- 메모리 낭비 이슈로 게시글 전체 조회 시 fetch join 삭제
> POST auth/email/send/temporary-password
1-1. 가입되지 않는 이메일인 경우 (404 error code 전달)
1-2. 소셜 로그인으로 가입한 이메일인 경우 (소셜 provider와 함께 409 error code 전달)
1-3. 일반 회원 가입으로 회원 가입한 회원인 경우 (200 http state code와 임시 비밀번호를 이메일로 전송) 
> GET /posts
- 좋아요한 사용자 리스트 최대 3개의 정보만 가져옴
- 댓글 리스트 조회 불가
<hr>
> GET /posts/{postId}
- 좋아요한 사용자 리스트 최대 3개의 정보만 가져옴
- 회원과 비회원이 동일한 게시글 조회 api를 사용하고, 인증 절차를 거치지 않으면 좋아요 및 북마크 여부 확인 불가능
- 해결: 회원과 비회원에게 다른 api를 제공 (회원: 인증이 필요한 api …

feat: 임시 비밀번호 발급 기능 추가 /  update:  JwtAuthenticationFilter, SecurityConfig에 인증 필요 없는 api 추가 및  게시글 조회 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/global/component/Scheduler.java

- 기능 추가
1. 정각에 LocalDateTime.now에 잡힌 예약 리스트 중 취소가 되지 않은 예약의 상태를 진행중으로 변경
2. 정각에 LocalDateTime.now 에서 1시간 뺀 시간에 잡힌 예약 중 진행 중인 예약 (한 시간 전에 시작된 예약)을 완료 상태로 변경
3. 트레이너의 예약 노쇼 처리 기능 추가 (완료 상태인 예약만 변경 가능, 진행 전/진행 중/취소 상태인거는 변경 불가능)
- 정각에 스케줄러 동작
- 노쇼 처리

Feature/training: 정각에 예약 상태 변경 스케줄러 추가, 트레이너의 예약 노쇼 처리 추가

---

src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java

- 수정
- main -> main
- user와 document 연관 관계 수정
- 회원 가입 시 프로필 이미지 업로드하지 않는 경우, DB에 저장된 디폴트 이미지로 등록 (Document 테이블의 Id가 1인 인스턴스)

update: user와 document 연관 관계 수정 (1:1에서 N:1)

---

src/main/java/com/fithub/fithubbackend/global/auth/OAuthFailureHandler.java

- 수정
- auth -> main
- 소셜 로그인 실패 시 원래는 /oauth/fail이었는데 프론트 요청으로 /login으로 변경
- url application.yml에서 가져오도록 수정
- application.yml에 security.registration.fail.redirect 부분 추가

update: 소셜 로그인 실패 리다이렉트 주소 변경

---

src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/BookmarkService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/BookmarkServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/LikesService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/LikesServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostDocumentService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostDocumentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/LikedUsersInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/LikesBookmarkStatusDto.java
src/main/java/com/fithub/fithubbackend/domain/board/post/domain/Post.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/BookmarkRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/LikesRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/PostRepository.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가, 수정
- 로그인한 사용자의 **게시글 좋아요, 북마크 여부** 확인 기능 추가
- 게시글 조회 api 수정
- **게시글 전체 조회 api** 
- GET /posts -> /posts/public 
- **게시글 세부 조회 api** 
- GET /posts/{postId} -> /posts/public/{postId}
- 게시글 좋아요한 사용자 정보 최대 4개까지 가져오도록 수정
- 좋아요한 사용자 리스트에 로그인한 사용자가 포함될 수 있어 **3개에서 4개로 수정**
**1. 로그인한 사용자의 게시글 좋아요, 북마크 여부 확인** 
1-1. 게시글 전체 조회
> GET /posts/like-and-bookmark-status
1-2. 게시글 세부 조회
> GET /posts/{postId}/like-and-bookmark-status

feat: 로그인한 사용자의 게시글 좋아요, 북마크 여부 확인 기능 추가 / update: 게시글 조회 api 수정, 게시글 좋아요한 사용자 정보 최대 4개까지 가져오도록 수정

---

src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserRepository.java

- 기능 수정
- main -> main
- UserDetailsServiceImpl의 `loadUserByUsername()` 까지 영속 상태이지만
JwtTokenProvider의 `getAuthentication()`에서 **준영속 상태**라 user.getProfileImg()으로 document를 가져오지 못하는 오류 발생
- 해결: 프로필 이미지 즉시 로딩(EAGER)으로 수정
> GET /users/profile

update: 프로필 이미지 즉시 로딩(EAGER) 으로 수정

---

src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/CommentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/LikesServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/api/EmailController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/EmailServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/auth/TokenInfoDto.java

- 기능 수정, 버그 수정
- main -> main
- 로그인 성공 시, Refresh Token 정보 제외한 Token Dto 전달
- 댓글 및 좋아요 알림 TODO 추가
- 임시 비밀번호 발급 HTTP 메소드 수정 (POST -> PATCH)
- 임시 비밀번호 발급 401 에러 수정
- 사용자의 provider가 null인 상태에서 isEmpty() 사용하면 NullPointerException 발생하므로 순서 변경
- 전체 게시글의 좋아요, 북마크 여부 체크 HTTP 메소드 수정 (GET -> POST)
1. 로그인 
> POST /auth/sign-in

update: Token Dto 에서 Refresh Token 제외, 댓글 및 좋아요 알림 TODO 추가, 일부 api HTTP 메소드 수정 / fix: 임시 비밀번호 401 에러 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingLikesController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingReservationController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingReservationService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingReservationServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/TrainingReview.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveCancelInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가, 수정
- 기존: 트레이니 전체 조회 시 삭제된 것만 제외했음 -> 변경: 마감된 트레이닝도 제외
- 트레이너가 예약을 노쇼 처리 했을 때 만약 그 전에 예약 회원이 리뷰를 작성했다면 비공개 처리
- 트레이닝 리뷰에 locked 추가
- 회원이 트레이닝 예약 전체 조회 시 피그마에 맞춰 진행전,진행,종료로 따로 조회 / 취소,노쇼 따로 조회로 분리
- 코드 에러 수정
- 트레이닝 전체 조회 (closed 제외 들어감)
- 노쇼 처리 시 리뷰 존재하면 lock 설정
- 트레이닝 예약 조회 수정
진행중,진행,종료 조회
취소,노쇼 조회

update/training: 트레이너가 예약 노쇼 처리 시 리뷰 존재하면 비공개 처리, 트레이닝 조회, 회원 예약 조회 수정

---

src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/api/UserPostCommentController.java
src/main/java/com/fithub/fithubbackend/domain/board/api/UserPostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostLikesService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostLikesServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/UserCommentService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/UserCommentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/UserPostService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/UserPostServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/CommentRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/LikesRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/PostRepository.java

- 기능 추가
- main -> main
- 회원이 작성한 게시글 조회 및 댓글 남긴 게시글 조회 기능 추가
- 단일 게시글에 대한 전체 좋아요 정보 조회 기능 추가 (페이징 사용)
1. 회원이 작성한 게시글 조회 (page 사용)
> GET /users/posts
2. 회원이 댓글 남긴 게시글 조회 (page 사용)
> GET /users/posts/comments
3. 단일 게시글에 대한 전체 좋아요 정보 조회 (page 사용)
> GET /posts/{postId}/likes/all

feat: 회원이 작성한 게시글과 댓글 남긴 게시글 조회, 단일 게시글의 전체 좋아요 정보 조회 기능 추가

---

.gitignore
src/main/java/com/fithub/fithubbackend/domain/Training/api/PaymentController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainerTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingLikesController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingLikeServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableDate.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/ReserveInfo.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainersTrainingOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/CancelReqDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/PaymentReqDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/ReserveReqDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/TrainersReserveInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableDateRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableTimeRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/CustomReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/CustomTrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingReviewRepository.java
src/main/java/com/fithub/fithubbackend/global/component/Scheduler.java
src/main/java/com/fithub/fithubbackend/global/exception/CustomExceptionHandler.java

- 기능 수정, 리팩토링
- 예약 리스트 조회 시 자기것만 가지고 오도록 수정
- 찜 설정 시 이미 찜한거면 에러 반환
- reserveInfo 엔티티가 availableDate, Time (예약 날짜, 시간)이랑 관계를 맺지 않았었음 -> 수정
- 결제 코드에서 불필요한 for문을 통해 데이터를 전부 찾아서 하나만 변경하게 되는 코드 대신 db에 접근하는 코드로 변경
- 결제 - 금액 검증 시 검증 실패하면 예약 취소하며 예약 시간을 enabled로 수정하지 않았었음 -> 수정하도록 변경 + CustomException 롤백 제외로 해서 검증 실패하면 변경 사항 업데이트 + reserveInfo 삭제하도록
- 결제 - 금액 검증 시 성공하면 결제 내역 대신 예약 id 반환으로 변경
- 트레이너의 트레이닝 목록 조회 기능 추가 (오픈 / 마감)
- 트레이너의 예약 리스트 조회 시 예약 상태에 따라 조회 하도록 수정 (진행중+진행전 / 완료 / 취소 / 노쇼)
- 트레이너가 트레이닝 하나에 대한 예약 리스트 조회 기능 추가 (예약 상태에 따라 조회,  진행중+진행전 / 완료 / 취소 / 노쇼)
- 결제 api 에러 핸들러, api에 필요한 파라미터가 없을 시 처리하는 핸들러 추가
- Q파일 수정 및 추가로 compileJava 필요
- 금액 검증 실패하면 (결제 금액과 트레이닝 금액이 다르면) 시간 예약 가능 상태 수정, reserveInfo 삭제
- impUid로 결제 정보 조회 실패
- 트레이너의 트레이닝 목록 조회
- 트레이너의 모든 예약 목록 조회 (status 없이 주면 BEFORE, START만 …

Update: 결제 관련 전부 수정, 리팩토링 / refactor: 스케줄러 리팩토링/ feat: 트레이너의 트레이닝 목록 조회, 예약 리스트 조회

---

src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PageableDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostSearchFilterDto.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostWriterInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/CustomPostRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/CustomPostRepositoryImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/PostRepository.java

- 기능 추가
- main -> main
- 게시글 검색 기능 추가
- 게시글 정보 dto에 작성자 이메일 (식별자 ) 추가
> POST /posts/search
- keyword: 검색 키워드
- scope :  검색 범위 ex) content(기본), writer, hashtags
- page : 페이지 번호 (기본 0 : 가장 첫 페이지), 필수 값
- size :한 페이지에 노출할 데이터 건수 (기본 9, 생략 가능)
- sort : 페이지 정렬 방식 (기본 id desc : 최신순, 생략 가능) ex) likes(좋아요 순), comments(댓글 순) 지정 가능

feat: 게시글 검색 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableDate.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/ReserveInfo.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingCreateDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/admin/repository/TrainerCareerTempRepository.java
src/main/java/com/fithub/fithubbackend/domain/admin/repository/TrainerLicenseTempImgRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCertificationRequest.java
src/main/java/com/fithub/fithubbackend/domain/user/api/UserController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java

- 에러 수정
- 프로필 업데이트 수정 (401 에러 난다고 해서 수정)
- detached된 유저여서 수정사항이 반영되지 않는 문제 save로 수정
- api 메서드를 사용하는 것 보다 put은 put의 역할만 하고 조회는 GET 메서드를 사용해 하도록 수정
- 트레이너 인증 요청 반려 시 temp 정보 (career, img) 삭제
- 트레이닝 수정: 이미지 추가 후 repo에서 이미지 찾고 없는 이미지 삭제하다보니 추가된 이미지도 삭제됨. 두 개를 바꿔서 먼저 기존에 없는 이미지 삭제 후 새로운 이미지 추가로 수정
- 트레이닝 날짜 수정: 기존에 있던 날짜를 삭제할 때 예약이 있는지 확인하는 코드에서 여러 개를 받아오는 find문인데 하나만 받아오도록 되어있어 에러 발생. List로 가져오도록 수정
- 트레이닝 삭제: soft delete로 하도록 했는데 트레이닝 삭제 시 예약이 아예 없었다면 아예 db에서 삭제 + soft delete 시에는 availableDate, Time도 close, delete 처리하도록 수정
1. 프로필 업데이트

fix: 프로필 코드 에러 수정, 트레이너,트레이닝 코드 에러 수정 및 업데이트

---

build.gradle
src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainerTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingLikesController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingReservationServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/Location.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainerInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainersTrainingOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/enums/Direction.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/CustomTrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthService.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerAuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/Trainer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareerTemp.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerCareerRequestDto.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java
src/main/java/com/fithub/fithubbackend/global/util/GeometryUtil.java

- 엔티티 수정
- 기능 추가
- 트레이너의 위치 -> 주소로 컬럼 수정
- db에서 geometry 사용을 위해 build에 hibernate-spatial 추가 (application.yml도 수정됨)
- 트레이너, 트레이너 경력, 트레이닝에 주소,좌표(경도,위도) 추가
- 트레이너 인증 요청,인증 승인 시 경도,위도 좌표 넣어주도록 수정
- 트레이닝 생성 시 트레이너의 현재 직장 좌표 사용
- 지정한 위치 2km 반경의 트레이닝 검색 기능 추가
- 주어진 목록의 트레이닝 찜 여부 조회 시 requestBody로 목록을 받아서 Get -> Post로 변경
- 트레이너 인증 요청 시 위도,경도,주소 넣기
- 트레이너 정보에 Point가 들어가있음
- 경도, 위도 보내주면 2km 반경의 트레이닝 검색 기능
[
{
"id": 3,
"trainerInfoDto": {
"trainerId": 2,
"name": "트레이너",
"trainerProfileImg": "https://fithub-bucket.s3.ap-northeast-2.amazonaws.com/profiles/1590f5b4-12b8-4ef4-a19f-4bf838dd2c60",
"address": "~"
},
"title": "작심삼일 타파2",
"price": 10000,
"address": "~",
"dist": 857.1267042646435,
"startDate": "2024-03-02",
"endDate": "2024-03-05",
"closed": false
},
{
"id": 4,
"trainerInfoDto": { …

Feature/training: 엔티티 수정, 지정한 위치 2km 반경 트레이닝 검색 기능 추가, fix: 목록의 트레이닝 찜 여부 조회 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainerTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerController.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerService.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/Trainer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerCareerDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerLicenseDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerSpecDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerCareerRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerLicenseImgRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가
- 사용자 프로필 업데이트 시, 사용자가 트레이너면 트레이너의 name도 변경 + 이미지 url도 변경하도록 수정
- 트레이너의 경력, 자격증 조회 기능 추가
- 트레이너의 경력 추가, 자격증 추가
- 트레이너의 경력 수정 기능 추가
- 트레이너의 경력, 자격증 삭제
- **트레이너 관련 api를 trainer -> trainers로 변경**
- 트레이너 스펙 조회
-트레이너 경력 추가
- 트레이너 자격증 추가
- 트레이너 경력 수정

feat: 트레이너 경력, 자격증 관련 작업 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainerTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/TrainingDateReservationNumDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingDateUpdateDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/TrainerCareer.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerCareerRepository.java

- 기능 추가
- 트레이너 경력 추가 시, 현재 재직중이라는 표시를 하면 트레이너의 근무지를 요청이 들어온 근무지로 변경 + 현재 트레이너가 만들어놓은 트레이닝 중 삭제X 마감X인 트레이닝의 근무지 변경
- 트레이너 경력 수정 시, 재직중이라는 표시를 하면 트레이너의 근무지 수정
- working = false로 수정 시,  삭제 X, 마감 X인 트레이닝이 있다면 에러 발생
- working = true로 수정 시, 경력 추가와 같게 동작

feat: 트레이너 경력 추가 및 수정 시 현 근무지 주소 업데이트 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainerTrainingController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java

- 기능 추가
- 트레이닝 생성 시, 날짜 중복을 피하기위해 트레이닝이 이미 있는 날짜는 불가능하게 해놔야됨. 그래서 이미 트레이닝이 있는 날짜(closed=false,delete=false)를 받아오는 api 추가

feat: 트레이닝 생성을 위해 트레이닝이 이미 있는 날짜 받아오는 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostService.java
src/main/java/com/fithub/fithubbackend/domain/board/application/PostServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/dto/PostSearchFilterDto.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/CustomPostRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/CustomPostRepositoryImpl.java

- 기능 수정
- main -> main
- 게시글 검색 기능 수정 (page 정보를 **dto**로 받는 대신 **pageable 파라미터**로 받도록 수정) 
- pageable
- ex) /posts/search?page=0&size=9&sort=id,desc
- page는 필수 / size와 sort는 선택 파라미터 (기본으로 size는 9, sort는 id desc)
- sort는 정렬 기준(ex id/likes/comments), 정렬 방향(ex desc/asc) 설정 가능. 정렬 기준과 방향을 ','를 사용하여 같이 설정해야 함. 
- 게시글 검색 dto
```
{
"keyword": "검색 키워드",
"scope": "content"
}
```

update: 게시글 검색 기능 수정 (page 정보를 dto로 받는 대신 pageable 파라미터로 받도록 수정)

---

src/main/java/com/fithub/fithubbackend/domain/Training/domain/AvailableDate.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingCreateDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableTimeRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/global/component/Scheduler.java

- 기능 수정
- 스케줄러에서 LocalDateTime.now()를 할 경우 서버의 date는 Asia/Seoul로 잡혀있는데 UTC 날짜로 계속 진행됨. 코드에서 Asia/Seoul 정보를 가져오도록 수정
- 트레이닝 위치가 트레이너 위치로 잡혀 트레이닝 생성 dto에서 받을 필요 없는 location 삭제

fix: 스케줄러 timezone 설정, 트레이닝 생성 시 필요없는  location 삭제

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/UserTrainingReservationController.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingReservationService.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingReservationServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveCompleteOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingReviewRepository.java
src/main/java/com/fithub/fithubbackend/global/exception/CustomExceptionHandler.java

- 기능 추가
- 트레이닝 예약 리스트 조회에서 종료된(COMPLETE) 리스트 받아오는 api 분리
- 종료된 예약은 리뷰 작성 또는 조회가 가능해야 하는데 해당 예약에 리뷰가 있는지 없는지를 알 수 있는 데이터가 응답 데이터에 포함되어 있어야 돼서 api 분리

feat: 트레이닝 예약 종료 리스트 조회 분리(리뷰 여부 필요해서)

---

src/main/java/com/fithub/fithubbackend/domain/user/api/UserController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/UserInterest.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/InterestUpdateDto.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/ProfileDto.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/SignUpDto.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserInterestRepository.java
src/main/java/com/fithub/fithubbackend/global/common/Category.java

- 기능 추가
- main -> main
- 회원의 관심사 수정 기능 추가
- 회원 가입 시 관심사 설정 기능 추가
- 회원의 프로필 조회 시 관심사도 조회하도록 수정
> POST /auth/sign-up
- **Request Body**
- **categories**: 필수 데이터가 아닌 관심사 리스트. 여러 개 선택 가능 (enum).  ex) PILATES, HEALTH, PT, CROSSFIT, YOGA
```
{
"email": "fithub2@fithub.com",
"password": "q1w2e3r4!",
"name": "name",
"nickname": "nickname",
"phone": "01012345678",
"gender": "F",
"categories": [
"PILATES", "YOGA"
]
}
```
> PUT /users/interest
- **Request Body**
- **interestsDeleted**: 관심사 삭제 여부
- **unModifiedInterests**: interestsDeleted = true 일 때만 사용. 삭제되지 않는 관심사. (enum)  ex) PILATES, HEALTH, PT, CROSSFIT, YOGA
- **interestsAdded**: 관심사 추가 여부
- **addedInterests**: 추가된 관심사 리스트  (enum)  ex) PILATES, HEALTH, PT, CROSSFIT, YOGA
```
{
"interestsDeleted": true,
"unModifiedInterests": [
"PILATES"
], …
```

feat: 회원의 관심사 수정 기능 추가, 회원 가입 시 관심사 설정 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/api/TrainingController.java
src/main/java/com/fithub/fithubbackend/domain/board/api/PostController.java

- 기능 수정
- RequestBody로 필터 조건을 받아왔는데 포스트맨에서는 가능했던게 스웨거, 프론트쪽 시도 시 설정한 데이터가 들어가지 않음을 발견. 
- 이유: RequestBody로 설정한 필터 조건들과 Pageable이 RequestBody로 처리되어 RequesyBody가 두 개인 것. 이렇게 다중 RequestBody는 Single Object만을 처리할 수 있도록 되어 있기 때문. 그래서 두 개의 RequestBody를 사용중인 우리 코드에서 받아오지 못했던것,
- 변경: RequestBody 대신 ModelAttribute(query) 사용. 이제 프론트에서는 query String으로 보내줘야됨
게시글

fix: 트레이닝 검색, 게시글 검색 시 requestBody로 데이터 못 받는 에러 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/application/TrainerTrainingServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/Training.java
src/main/java/com/fithub/fithubbackend/domain/Training/domain/TrainingCategory.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingCategoryUpdateDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingContentUpdateDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/trainersTraining/TrainingCreateDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingCategoryRepository.java

- 기능 추가
- main -> main
- 트레이닝 카테고리 설정 기능 추가
> PUT /trainers/training
1. 수정된 카테고리 X
- trainingCategoryUpdateDto의 **unModifiedCategoryList**, **newCategoryList**: 빈 리스트 형태로 전달. 
<hr>
2. 삭제된 카테고리 O
- categoryDeleted: true 설정
- unModifiedCategoryList: 삭제되지 않는 카테고리 리스트
<hr>
3. 추가된 카테고리 O
- categoryAdded: true 설정
- newCategoryList: 새로 추가된 카테고리 리스트
- 트레이닝의 카테고리 null 허용 여부 (현재는 null  허용)
- **2024-03-11 update**
- @NotEmpty 설정하여 null 허용 X
- 트레이닝 생성 시 카테고리 리스트를 안 보내거나 빈 리스트로 전달 받을 시, 검증 실패 메시지 출력

feat: 트레이닝 카테고리 설정 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingReservationServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/TrainingSearchConditionDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveCompleteOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveInfoDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/dto/review/UsersTrainingReviewDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/CustomTrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java

- 기능 추가, 수정
- 트레이닝 검색 시 카테고리 추가
- 회원의 트레이닝 예약 정보, 후기 조회 시에 트레이너 프로필 이미지 필요해서 dto에 추가
- 회원의 트레이닝 예약 정보 조회 시 querydsl 사용할 필요가 없어서 jpa로 변경
- 트레이닝 검색 시 카테고리
- 회원의 트레이닝 예약 정보, 후기 조회 시 트레이너 프로필 이미지 추가
- 후기 조회 시 트레이너 프로필 이미지 추가
- queryProjection 삭제로 compileJava 필요

Update: 트레이닝 예약 정보 조회, 후기 조회 프로필 이미지 추가, 로직 변경 / feat: 트레이닝 검색 시 카테고리 필터 추가

---

src/main/java/com/fithub/fithubbackend/domain/board/dto/PostSearchFilterDto.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/CustomPostRepositoryImpl.java

- 에러 수정
- main -> main
- 키워드 없이 페이지 정렬 조건으로 게시글 검색 시 **401 에러 발생** 
- **발생 원인** : 검색 필터 DTO 중 검색 범위(scope)가 null 인 경우, 디폴트 값으로 지정된 "content"로 바인딩 되지 않음. 생성자에도 기본값이 설정되어 있지 않음.
- **해결** : 검색 범위의 디폴트로 지정된 값 삭제 및 CustomPostRepositoryImpl에 조건문 추가

fix: 키워드 없이 페이지 정렬 조건으로 게시글 검색 시 401 에러 발생 해결

---

src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerSearchController.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerSearchService.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerSearchServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerSearchFilterDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/CustomTrainerRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/CustomTrainerRepositoryImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/UserInterest.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가
- main -> main
- 트레이너 검색 기능 추가
- 관심사 엔티티에 @JsonIgnore 사용하여 불필요한 속성(user) 제외
> GET /search/trainers
- **request parameters** 
- **interest**: 1개의 관심사(PILATES, HEALTH, PT, CROSSFIT, YOGA)
- **keyword**: 검색 키워드(트레이너 이름)
- **gender**: 트레이너 성별
- **request URL**
- ex) http://localhost:8080/search/trainers?page=0&interest=YOGA&gender=F
- **/trainers/search** 를 사용하면 트레이너 인증이 필요한 api와 구분되지 않으므로, **/search/trainers**로 변경
- 문제
-  검색 필터를 **파라미터**로, 페이징을 **request body**로 전달 받으면, 전달 받은 페이징으로 적용되지 않는 문제 발생 
- 페이징을 검색 필터와 같이 **파라미터**로 전달해야 페이징 적용
- 해결
-  POST 대신 **GET**을 사용하여 검색 필터와 페이징을 **파라미터**로 전달

feat: 트레이너 검색 기능

---

src/main/java/com/fithub/fithubbackend/domain/Training/dto/reservation/UsersReserveOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingReviewRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerSearchController.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerSearchService.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerSearchServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerSearchAllReviewDto.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java

- 기능 추가
1. 회원의 마이페이지 - 예약 내역 조회에 가격 정보 추가
2. 트레이너 검색 시, 해당 트레이너의 모든 리뷰 조회 기능 추가
- 트레이너의 모든 리뷰 조회 기능 (최신순 정렬)

Update: 회원의 트레이닝 예약 내역에 가격 정보 추가, Feat: 트레이너 검색 시, 해당 트레이너의 모든 리뷰 조회 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/user/dto/map/MapDocument.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/map/MapResDto.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/map/Meta.java
src/main/java/com/fithub/fithubbackend/global/util/KakaoMapUtil.java

- 기능 추가
- update -> main
- 좌표로 행정 구역 정보 받기 
- 카카오맵 api
- https://developers.kakao.com/docs/latest/ko/local/dev-guide#coord-to-district-response-body-meta

feat: 좌표로 행정 구역 정보 받기 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/trainer/api/TrainerSearchController.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerSearchService.java
src/main/java/com/fithub/fithubbackend/domain/trainer/application/TrainerSearchServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerOutlineDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerSearchAllLicenseDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/dto/TrainerSearchCompanyDto.java
src/main/java/com/fithub/fithubbackend/domain/trainer/repository/TrainerLicenseImgRepository.java

- 기능 추가
- main -> main
- 트레이너 상세 조회 기능 추가
> /search/trainers/{trainerId}
- **address**: 현재 근무 중인 회사 주소 
- **id**: 트레이너 id (pk)
- **name**: 트레이너 성명
- **email**: 이메일
- **profileUrl**: 프로필 이미지 url
- **interests**: 트레이너 전문 분야
<hr>
> /search/trainers/licenses
- **totalCounts**: 자격증 수
- **licenses**: 자격증 정보 
- **licenseId**: 자격증 id (pk)
- **url**: 자격증 이미지 url
- **inputName**: 자격증 명
<hr>
> /search/trainers/company
- **company**: 현재 근무 중인 회사명
- **latitude**: 회사 위치의 위도 
- **longitude**: 회사 위치의 경도

feat: 트레이너 상세 조회 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/application/UserTrainingReservationServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/admin/application/AdminServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/domain/Notify.java
src/main/java/com/fithub/fithubbackend/global/notify/NotificationType.java
src/main/java/com/fithub/fithubbackend/global/notify/NotifyListener.java
src/main/java/com/fithub/fithubbackend/global/notify/controller/NotifyController.java
src/main/java/com/fithub/fithubbackend/global/notify/dto/NotifyDto.java
src/main/java/com/fithub/fithubbackend/global/notify/dto/NotifyRequestDto.java
src/main/java/com/fithub/fithubbackend/global/notify/repository/NotifyRepository.java
src/main/java/com/fithub/fithubbackend/global/notify/service/NotifyService.java
src/main/java/com/fithub/fithubbackend/global/notify/service/NotifyServiceImpl.java

- 기능 추가
- Notify 엔티티 추가
- 알림 SSE가 아닌 소켓으로 사용
- SSE 코드 만들었으나 open-in-view=false 설정 시 너무 많은 에러 확인. 고치기 힘든 부분이 많음 + nginx 에서 제대로 돌아갈지 모르겠음 -> 채팅으로 소켓 사용하니 그냥 소켓으로 실시간 알림 보내도록
- 이벤트 리스너 사용으로 알림 보내도록
- ApplicationEventPublisher의 publishEvent 호출하면 NotifyListener로 이동함
- 읽지 않은 알림 개수 조회
- 모든 알림 조회(page, size = 5)
- 선택한 알림 읽음 처리
- 선택한 알림 삭제, 선택 리스트 삭제
후기 작성 시
구독한 사용자에게 알림 감 (사용자가 실시간으로 접속해 있어야 볼 수 있음)
- 읽지 않은 알림 개수 조회
- 알림 목록 조회
@Songhee120 저희 소켓 통신을 /ws/chat으로 잡았는데 알림에도 쓰니까 /chat 없애고 fithub을 쓰거나 그냥 /ws 까지만 쓰는 거 어떨까요?? 그리고 chat 폴더에 있는 StompConfig와 handler 파일은 global 폴더로 옮기는 게 좋을 것 같은데 어떠신가요?

Notify: 알림 기능 소켓으로 사용 추가, 알림 기능들 추가

---

src/main/java/com/fithub/fithubbackend/domain/chat/api/ChatMessageController.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageService.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/domain/ChatMessage.java
src/main/java/com/fithub/fithubbackend/domain/chat/dto/ChatMessageResponseDto.java
src/main/java/com/fithub/fithubbackend/domain/chat/dto/ChatRoomResponseDto.java
src/main/java/com/fithub/fithubbackend/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
src/main/java/com/fithub/fithubbackend/global/config/stomp/StompConfig.java
src/main/java/com/fithub/fithubbackend/global/config/stomp/StompHandler.java

- 기능 추가
- 기능 수정
- 파일 위치 변경
- main -> main
- 채팅 메세지 조회 기능 추가 
- 채팅방 목록 조회 응답 데이터 추가
- stomp 설정 파일(config, handler) 위치 변경(global/config/stomp)
- 웹소켓 연결 요청 경로 변경 /ws/chat -> /ws
**'안읽은메세지개수(unreadChatCount)' 기능 구현 아직 되지 않은 관계로 우선 초기값 0으로 작성해두었습니다.**

feat: 채팅 메세지 조회

---

src/main/java/com/fithub/fithubbackend/domain/Training/application/PaymentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableDateRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/AvailableTimeRepository.java

- 기능 수정
- 예약 동시성 문제를 해결하기 위해 기존에는 예약 시간 저장 api 에서 availableDate에 lock을 걸었으나 그 후에 availableTime에서 제대로 수정사항을 읽지 못 하는 걸 확인함
- date대신 time에 lock으로 수정
쓰레드로 테스트 시, 먼저 접근한 시간이 수정되면 그 후에 제대로 불가능한 시간으로 수정된 데이터를 읽고 오는 걸 확인함
```
2024-04-08 16:55:01.073  [TIME] - availableTimeRepository.findById, 트레이너입니다
2024-04-08 16:55:01.076  [TIME] - availableTimeRepository.findById, 서가람
Hibernate: 
select
...
from
available_time a1_0 
where
a1_0.id=? 
and (
a1_0.deleted = 0
) for update wait 3
Hibernate: 
select
...
from
available_time a1_0 
where
a1_0.id=? 
and (
a1_0.deleted = 0
) for update wait 3
2024-04-08 16:55:01.095  [TIME] - availbleTime: 63 true 서가람
Hibernate: 
update
available_time 
set
available_date_id=?,
deleted=?,
enabled=?,
time=? 
where
id=?
Hibernate: 
select
a1_0.id 
from
available_time a1_0 …
```

fix: 예약 동시성 문제 date가 아닌 time에 Lock으로 수정

---

src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingLikesRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/BookmarkRepository.java
src/main/java/com/fithub/fithubbackend/domain/board/repository/LikesRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/api/UserController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserService.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/ClosureReason.java
src/main/java/com/fithub/fithubbackend/domain/user/domain/User.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/CloseAccountReasonDto.java
src/main/java/com/fithub/fithubbackend/domain/user/enums/ClosureReasonType.java
src/main/java/com/fithub/fithubbackend/domain/user/enums/Status.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/ClosureReasonRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserInterestRepository.java

- 기능 추가
- main -> main
- 탈퇴 전 탈퇴 사유 선택 및 입력
- **관심사, 게시글 좋아요 및 북마크, 트레이닝 찜** 삭제
- **회원의 개인 정보** (이메일, 비밀번호, 전화번호, 성별, 자기소개, roles 등)  null 또는 빈 문자열(””)로 변경
- 회원 프로필 이미지가 기본 이미지가 아니라면, **기존 이미지 삭제 후 기본 이미지**로 변경
- 작성한 게시글, 댓글, 트레이닝 후기에 "**탈퇴 회원**"으로 표시되도록 **사용자 이름 및 닉네임** 변경
- DB에 탈퇴 회원으로 알도록 수정 ( soft delete / **status**를 **DELETE**로 변경)
- **예약되거나 진행 중인 트레이닝**이 있을 경우 탈퇴 보류 (**400 error** 발생)
> PUT /users
**Request body**
- closureReasonType: 탈퇴 사유 (**INSUFFICIENT_FACILITIES(원하는 시설 부족), 
UNSATISFACTORY_SERVICE(고객 응대에 대한 불만족, LOW_USAGE(낮은 사용 빈도), OTHER(기타)** 중 택 1)
- customReason: closureReasonType 이 "OTHER" 일 경우 값 전달. 회원이 직접 탈퇴 사유 입력.
<hr>
- **예약되거나 진행 중인 트레이닝**이 있을 경우 탈퇴 보류 (**400 error** 발생)

feat: 일반 회원 탈퇴 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/chat/api/ChatMessageController.java
src/main/java/com/fithub/fithubbackend/domain/chat/api/ChatRoomController.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomService.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/domain/Chat.java
src/main/java/com/fithub/fithubbackend/domain/chat/domain/ChatMessage.java
src/main/java/com/fithub/fithubbackend/domain/chat/dto/ChatRoomResponseDto.java
src/main/java/com/fithub/fithubbackend/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/fithub/fithubbackend/domain/chat/repository/ChatRepository.java
src/main/java/com/fithub/fithubbackend/domain/user/api/AuthController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/AuthServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/config/stomp/StompHandler.java

- 기능 추가
- 기능 수정
- main -> main
- 로그인 시, /topic/alarm/{userId} 구독
- 새로운 메세지 전송하면 /queue/alarm/{userId}로 '새로운 채팅!' 발행
- unreadChatCnt 0: 안 읽은 메세지 없음
- unreadChatCnt 1: 안 읽은 메세지 있음
- 채팅방 없을 시: 채팅방 생성 후 메세지 내용 조회
- 채팅방 있을 시: 바로 메세지 내용 조회
경로 'notification'에서 'alarm' 으로 변경해뒀습니다.
채팅 생성 api 다시 남겨뒀습니다.

feat: 채팅 메세지 알림 기능, 채팅방 목록 조회 데이터 추가

---

src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/auth/JwtAuthenticationFilter.java
src/main/java/com/fithub/fithubbackend/global/config/SecurityConfig.java
src/main/java/com/fithub/fithubbackend/global/config/stomp/StompConfig.java
src/main/java/com/fithub/fithubbackend/global/config/stomp/StompHandler.java
src/main/java/com/fithub/fithubbackend/global/notify/service/NotifyServiceImpl.java

- 수정
- 서버에 배포하면 웹소켓 연결 안 되는 문제
-  설정에서 setAllowedOrigins -> setAllowedOriginPatterns으로 수정. 현재 cors설정에서 allowCredentials=true라 해당 설정이 아닌 originPatterns를 사용해야됨
- /ws -> /ws/stomp 변경
- 웹소켓 설정에서 /topic, /queue 둘 다 구독 용도라는 걸 알게되고 수정, 클라이언트가 보낼 때는 /app을 사용하도록 수정
- Stomphandler에서 jwt 검사로 인증된 사용자만 가능하도록 코드 추가 (현재는 주석, 프론트 코드 된 것 같으면 수정)
- 로그인 시, 프론트에서 가지고 있는 정보는 이메일이라 알림 구독을 사용자 id가 아닌 이메일로 수정

Fix: ec2에서 웹소켓 연결 에러 수정, 알림 구독 사용자id -> email로 변경

---

src/main/java/com/fithub/fithubbackend/domain/chat/api/ChatMessageController.java
src/main/java/com/fithub/fithubbackend/domain/chat/api/ChatRoomController.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageService.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomService.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/dto/ChatMessageResponseDto.java
src/main/java/com/fithub/fithubbackend/domain/chat/repository/ChatMessageRepository.java

- 수정
- main-> main
- 채팅방 존재 여부 체크 기능: 채팅방 id 리턴으로 변경
- 채팅방 생성 기능: 채팅방 id 리턴으로 변경
- 메세지 응답 dto isMe 데이터 추가
- 메세지 조회 시 정렬 날짜 기준 오름차순

update: 채팅방 api 반환값 수정, 메세지 조회 반환값 데이터 추가

---

src/main/java/com/fithub/fithubbackend/domain/Training/repository/ReserveInfoRepository.java
src/main/java/com/fithub/fithubbackend/domain/Training/repository/TrainingRepository.java
src/main/java/com/fithub/fithubbackend/domain/trainer/domain/Trainer.java
src/main/java/com/fithub/fithubbackend/domain/user/api/UserController.java
src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
src/main/java/com/fithub/fithubbackend/global/exception/ErrorCode.java

- 기능 추가
- main -> main
- `탈퇴 회원` 으로 표시되도록 트레이너 이름 수정
- 이메일을 빈 문자열로 변경
- 트레이너의 현재 재직 중인 회사 주소와 위도 경도 `null `로 변경
- 트레이너 프로필 이미지를 **기본 이미지**로 변경
- 예약되거나 진행 중인 트레이닝이 있을 경우 탈퇴 보류 (`400` error 발생)
- 모집 중인 트레이닝이 있을 경우 탈퇴 보류 (`409` error 발생)
> PUT /users
**Request body**
- closureReasonType: 탈퇴 사유 (**INSUFFICIENT_FACILITIES(원하는 시설 부족), 
UNSATISFACTORY_SERVICE(고객 응대에 대한 불만족), LOW_USAGE(낮은 사용 빈도), OTHER(기타)** 중 택 1)
- customReason: closureReasonType 이 "OTHER" 일 경우 값 전달. 회원이 직접 탈퇴 사유 입력.
<hr>
- **예약 또는 진행 중인 트레이닝**이 있을 경우 탈퇴 보류 (**400 error** 발생)
- **모집 중인 트레이닝**이 있을 경우 탈퇴 보류 (**409 error** 발생)

feat: 트레이너 탈퇴 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/user/application/UserServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/user/dto/InterestUpdateDto.java
src/main/java/com/fithub/fithubbackend/domain/user/repository/UserInterestRepository.java

- 기능 수정
- main -> main
- 관심사 업데이트 dto 수정
- 변경 전 : 관심사 추가/삭제 여부, 관심사 추가/삭제된 리스트
- 변경 후 :  **관심사 수정 여부**, **관심사 리스트**
- 삭제된 관심사를 일괄 delete 처리하기 위해 쿼리 개선
- 기존 쿼리: 1건씩 데이터 delete
`userInterestRepository.delete(originalInterest);` 
- 수정 쿼리: @Query를 통해 쿼리를 직접 작성하여 데이터 일괄 delete
```
@Modifying
@Query("delete from UserInterest u where u.user = :user and u.interest in :interests")
void deleteAllByUserAndInterests(@Param("user") User user, @Param("interests")List<Category> interests);
```
[https://velog.io/@isayaksh/JPA-%EB%8C%80%EB%9F%89%EC%9D%98-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%9D%BC%EA%B4%84-DELETE-%EC%BF%BC%EB%A6%AC-%EA%B0%9C%EC%84%A0](url)

update: 관심사 업데이트 dto 필드 수정

---

src/main/java/com/fithub/fithubbackend/domain/chat/api/ChatRoomController.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomService.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatRoomServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/domain/Chat.java
src/main/java/com/fithub/fithubbackend/domain/chat/domain/ChatPK.java
src/main/java/com/fithub/fithubbackend/domain/chat/repository/ChatRepository.java

- 기능 추가
- 채팅방 나가기 (삭제) 기능 추가
1:1 채팅이므로 사용자 한 명이 나가면 다른 사용자는 그걸 알 수 있어야 됨 -> chat에 deleted 추가
deleted인 chat은 가져오지 않도록 수정해서 내가 그 채팅방을 나간 사용자면 chatRoomList에서 볼 수 없음
채팅방에서 모든 사용자가 나가야 채팅방 아예 삭제. 한 명의 사용자만 나갔으면 접근은 가능하도록

feat: 채팅방 삭제 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/board/application/UserCommentServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/board/application/UserPostLikesServiceImpl.java

- 기능 추가
- main -> main
- 게시글 좋아요 시,  게시글 작성자에게 알림 전송 
- 자신의 게시글에 좋아요 누를 시, **알림 전송 X** 
<hr>
- 게시글 댓글 남길 시, 게시글 작성자 또는 부모 댓글 작성자에게 알림 전송
NO | 게시글 작성자 | 댓글 작성자 | 부모 댓글 작성자 | 결과 
-- | -- | -- | -- | -- | 
1 | A | A | A | 알림 전송 X 
2 | A | A | B | 부모 댓글 작성자에게 알림 전송
3 | B | A | A | 게시글 작성자에게 알림 전송
4 | B | A | B | 게시글 작성자에게 알림 전송
5 | B | A | C | 게시글 작성자, 부모 댓글 작성자에게 알림 전송
6 | B | A | null |  게시글 작성자에게 알림 전송
- 게시글 작성자에게 알림 전송 시 `comment.getUser().getNickname()님이 회원님의 게시글에 댓글을 남겼습니다.` 문구 전송
- 부모 댓글 작성자에게 알림 전송 시 `comment.getUser().getNickname()님이 회원님의 댓글에 답글을 남겼습니다.` 문구 전송

feat: 게시글 좋아요 및 댓글 알림 기능 추가

---

src/main/java/com/fithub/fithubbackend/domain/chat/api/ChatMessageController.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageService.java
src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageServiceImpl.java

- 기능 수정
main -> main
ws으로 채팅 전송 시 발행되는 채팅 응답 데이터 추가 (chatMessageResponseDto 리턴)

update: 채팅 메세지 ws 발행 시, 데이터 추가

---

src/main/java/com/fithub/fithubbackend/domain/chat/application/ChatMessageServiceImpl.java
src/main/java/com/fithub/fithubbackend/domain/chat/dto/ChatMessageResponseDto.java

- 기능 수정
main -> main
ws으로 채팅 전송 시 발행되는 채팅 응답 데이터 추가 (chatMessageResponseDto 리턴 + **email 데이터 추가**)

update: 채팅 메세지 ws 발행 시, 발신자 이메일 데이터 추가
